<?xml version="1.0" encoding="utf-8"?><Database Name="C:\CodePlex\tagomatique\Tagomatique\Tagomatique.sdf" Class="SQLCompactContext" Provider="SQLCompact" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="Chapitre">
    <Type Name="Chapitre">
      <Column Name="ID_Chapitre" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Debut" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Fin" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="FK_ID_Media" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Dossier">
    <Type Name="Dossier">
      <Column Name="ID_Dossier" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Chemin" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Infos">
    <Type Name="Infos">
      <Column Name="version" Member="Version" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Media">
    <Type Name="Media">
      <Column Name="ID_Media" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RelativeURL" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="FK_ID_Dossier" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Signet">
    <Type Name="Signet">
      <Column Name="ID_Signet" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Duree" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Libelle" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FK_ID_Media" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Tag">
    <Type Name="Tag">
      <Column Name="ID_Tag" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Libelle" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FK_ID_Media" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FK_ID_Chapitre" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
</Database>