//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tagomatique.Supplies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tagomatique.Supplies.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter Dossier.
        /// </summary>
        public static string AjouterDossier {
            get {
                return ResourceManager.GetString("AjouterDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter Dossier Relatif.
        /// </summary>
        public static string AjouterDossierRelatif {
            get {
                return ResourceManager.GetString("AjouterDossierRelatif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter Média.
        /// </summary>
        public static string AjouterMedia {
            get {
                return ResourceManager.GetString("AjouterMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter Média Relatif.
        /// </summary>
        public static string AjouterMediaRelatif {
            get {
                return ResourceManager.GetString("AjouterMediaRelatif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Annuler {
            get {
                return ResourceManager.GetString("Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Média(s) : {0}.
        /// </summary>
        public static string NombreMedia {
            get {
                return ResourceManager.GetString("NombreMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Média(s) Invalide(s) : {0}.
        /// </summary>
        public static string NombreMediaInvalide {
            get {
                return ResourceManager.GetString("NombreMediaInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Média(s) Valide(s) : {0}.
        /// </summary>
        public static string NombreMediaValide {
            get {
                return ResourceManager.GetString("NombreMediaValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Musique(s) : {0}.
        /// </summary>
        public static string NombreMusique {
            get {
                return ResourceManager.GetString("NombreMusique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Photo(s) : {0}.
        /// </summary>
        public static string NombrePhoto {
            get {
                return ResourceManager.GetString("NombrePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Vidéo(s) : {0}.
        /// </summary>
        public static string NombreVideo {
            get {
                return ResourceManager.GetString("NombreVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescaner le(s) dossier(s) déjà ajouté.
        /// </summary>
        public static string RescannerDossierDejaAjouter {
            get {
                return ResourceManager.GetString("RescannerDossierDejaAjouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez selectionné le dossier à ajouté.
        /// </summary>
        public static string SelectionnerDossier {
            get {
                return ResourceManager.GetString("SelectionnerDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez selectionné le(s) fichier(s) à ajouté(s).
        /// </summary>
        public static string SelectionnerFichier {
            get {
                return ResourceManager.GetString("SelectionnerFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag(s) disponible(s).
        /// </summary>
        public static string TagsDisponibles {
            get {
                return ResourceManager.GetString("TagsDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag(s) selectionné(s).
        /// </summary>
        public static string TagsSelectionner {
            get {
                return ResourceManager.GetString("TagsSelectionner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string Valider {
            get {
                return ResourceManager.GetString("Valider", resourceCulture);
            }
        }
    }
}
