//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.296
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tagomatique.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tagomatique.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter Dossier.
        /// </summary>
        public static string AjouterDossier {
            get {
                return ResourceManager.GetString("AjouterDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter Dossier Relatif.
        /// </summary>
        public static string AjouterDossierRelatif {
            get {
                return ResourceManager.GetString("AjouterDossierRelatif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter Média.
        /// </summary>
        public static string AjouterMedia {
            get {
                return ResourceManager.GetString("AjouterMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter Média Relatif.
        /// </summary>
        public static string AjouterMediaRelatif {
            get {
                return ResourceManager.GetString("AjouterMediaRelatif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string Annuler {
            get {
                return ResourceManager.GetString("Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de Média(s) : {0}.
        /// </summary>
        public static string NombreMedia {
            get {
                return ResourceManager.GetString("NombreMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de Média(s) Invalide(s) : {0}.
        /// </summary>
        public static string NombreMediaInvalide {
            get {
                return ResourceManager.GetString("NombreMediaInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de Média(s) Valide(s) : {0}.
        /// </summary>
        public static string NombreMediaValide {
            get {
                return ResourceManager.GetString("NombreMediaValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de Musique(s) : {0}.
        /// </summary>
        public static string NombreMusique {
            get {
                return ResourceManager.GetString("NombreMusique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de Photo(s) : {0}.
        /// </summary>
        public static string NombrePhoto {
            get {
                return ResourceManager.GetString("NombrePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de Vidéo(s) : {0}.
        /// </summary>
        public static string NombreVideo {
            get {
                return ResourceManager.GetString("NombreVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rescaner le(s) dossier(s) déjà ajouté.
        /// </summary>
        public static string RescannerDossierDejaAjouter {
            get {
                return ResourceManager.GetString("RescannerDossierDejaAjouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionné le dossier à ajouté.
        /// </summary>
        public static string SelectionnerDossier {
            get {
                return ResourceManager.GetString("SelectionnerDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionné le(s) fichier(s) à ajouté(s).
        /// </summary>
        public static string SelectionnerFichier {
            get {
                return ResourceManager.GetString("SelectionnerFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tag(s) disponible(s).
        /// </summary>
        public static string TagsDisponibles {
            get {
                return ResourceManager.GetString("TagsDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tag(s) selectionné(s).
        /// </summary>
        public static string TagsSelectionner {
            get {
                return ResourceManager.GetString("TagsSelectionner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        public static string Valider {
            get {
                return ResourceManager.GetString("Valider", resourceCulture);
            }
        }
    }
}
